name: sc-tutorial
channels:
 - conda-forge
 - bioconda
dependencies:
 - python>=3.5, <3.7
 - cmake>=3.9, <3.11
 - r-essentials
 - r-rgl
 - pandas
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - gsl
 - tzlocal
 - simplegeneric
 - natsort
 - h5py
 - tqdm
 - patsy
 - llvmlite
 - numba
 - networkx
 - joblib
 - numexpr
 - pytables
 - seaborn
 - statsmodels
 - python-igraph
 - louvain
 - r-rngtools
 - bioconductor-rhdf5lib
 - pip
 - pip:
   - MulticoreTSNE
   - anndata
   - fa2
   - gprofiler-official
   - scanpy
   - rpy2
   - git+https://github.com/flying-sheep/anndata2ri
   
